package io.github.jakediscord.hobbymod.winery;

import java.io.IOException;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

final class WineBatchTest {
    private static WineBatch fruit(boolean red,int age){return WineBatch.press(Collections.nCopies(8,new WineBatch.Fruit(red,age,true)),82);}
    private static WineBatch aged(){var b=fruit(true,4);b.start(0,true);b.advance(1200,false,true);b.rack(1200);b.advance(3600,false,true);return b;}
    @Test void ripenessAndCompositionGiveDistinctWineStyles(){var firm=fruit(true,3);var ripe=fruit(true,4);var late=fruit(false,5);var over=fruit(false,6);assertTrue(firm.sugar<ripe.sugar);assertTrue(firm.acidity>ripe.acidity);assertTrue(ripe.quality()>firm.quality());assertTrue(over.quality()<late.quality());assertEquals(WineBatch.Kind.WHITE,late.kind());var mixed=new ArrayList<WineBatch.Fruit>();mixed.addAll(Collections.nCopies(4,new WineBatch.Fruit(true,4,true)));mixed.addAll(Collections.nCopies(4,new WineBatch.Fruit(false,5,false)));var rose=WineBatch.press(mixed,82);assertEquals(WineBatch.Kind.ROSE,rose.kind());assertEquals(50,rose.red);assertThrows(IllegalArgumentException.class,()->WineBatch.press(mixed.subList(0,7),82));}
    @Test void fermentationRequiresRackingBeforeAging(){var b=fruit(true,4);assertFalse(b.rack(0));assertTrue(b.start(0,true));assertFalse(b.start(0,true));b.advance(9000,false,true);assertEquals(WineBatch.Stage.READY_TO_RACK,b.stage);assertEquals(1200,b.fermented);assertEquals(7800,b.rested);assertEquals(0,b.aged);assertTrue(b.rack(9000));b.advance(11400,false,true);assertEquals("Balanced",b.ageLabel());assertEquals(2400,b.aged);}
    @Test void unloadedElapsedTimeMatchesSparseContinuousSimulation(){var sparse=fruit(true,4);var jump=sparse.copy();sparse.start(50,true);jump.start(50,true);for(int t=70;t<=1250;t+=20)sparse.advance(t,false,true);jump.advance(1250,false,true);sparse.rack(1250);jump.rack(1250);for(int t=1270;t<=3650;t+=20)sparse.advance(t,false,true);jump.advance(3650,false,true);assertArrayEquals(sparse.encode(),jump.encode());}
    @Test void restartsAndClockRollbacksDoNotDoubleCount()throws Exception{var b=fruit(true,4);b.start(100,true);b.advance(700,false,true);b=WineBatch.decode(b.encode());b.advance(300,false,true);b.advance(700,false,true);assertEquals(600,b.fermented);b.advance(800,false,true);assertEquals(700,b.fermented);b.lastClock=900;b.advance(Long.MAX_VALUE,false,true);assertEquals(1200,b.fermented);assertTrue(b.rested<=24000L*365);}
    @Test void cleanCoolDarkConditionsAndTimelyAgingImproveQuality(){var good=aged();var cloudy=fruit(true,4);cloudy.start(0,false);cloudy.advance(1200,true,false);cloudy.rack(1200);cloudy.advance(3600,true,false);assertTrue(cloudy.quality()<good.quality());assertTrue(cloudy.tastingNotes().contains("cloudy"));int peak=good.quality();good.advance(25000,false,true);assertTrue(good.quality()<peak);assertEquals("Past its peak",good.ageLabel());}
    @Test void labeledBatchesRoundTripAndCopiesRemainIndependent()throws Exception{var b=aged().bottled("  Jacob's vintage §\n");var copy=WineBatch.decode(b.encode());assertEquals(b.id,copy.id);assertArrayEquals(b.encode(),copy.encode());assertEquals(b.tastingNotes(),copy.tastingNotes());assertFalse(copy.label.contains("§"));copy.remaining--;assertEquals(4,b.remaining);assertEquals(82,b.vintage);assertTrue(b.encode().length<WineBatch.MAX_BYTES);}
    @Test void malformedAndOversizedBatchesAreRejected()throws Exception{var b=aged();var bytes=b.encode();for(int n:new int[]{0,31,bytes.length-1})assertThrows(IOException.class,()->WineBatch.decode(Arrays.copyOf(bytes,n)));assertThrows(IOException.class,()->WineBatch.decode(new byte[WineBatch.MAX_BYTES+1]));assertThrows(IOException.class,()->WineBatch.decode(Arrays.copyOf(bytes,bytes.length+1)));var bad=bytes.clone();bad[0]=0;assertThrows(IOException.class,()->WineBatch.decode(bad));b.remaining=5;assertThrows(IOException.class,()->WineBatch.decode(b.encode()));b.remaining=4;b.badFerment=1201;assertThrows(IOException.class,()->WineBatch.decode(b.encode()));}
    @Test void duplicateBatchIdsCannotChangeWineOrMintAdditionalBottles(){var b=aged().bottled("First vintage");var ledger=new WineLedger();assertTrue(ledger.finish(b));var copy=b.copy();copy.label="Counterfeit";assertFalse(ledger.finish(copy));assertEquals("First vintage",ledger.get(b.id).wine().label);assertEquals(1,ledger.issue(b.id,1));assertEquals(3,ledger.issue(b.id,20));assertEquals(0,ledger.issue(b.id,1));assertEquals(0,ledger.remaining(b.id));}
    @Test void issueCountPersistsAcrossLedgerReloadAndRecordCopies(){var b=aged().bottled("Cellar");var old=new WineLedger();old.finish(b);old.issue(b.id,2);var restored=new WineLedger();restored.restore(old.get(b.id).wine(),old.get(b.id).issued());var leaked=restored.get(b.id).wine();leaked.label="Changed";assertEquals("Cellar",restored.get(b.id).wine().label);assertEquals(2,restored.issue(b.id,4));assertEquals(0,restored.issue(b.id,1));assertEquals(0,restored.issue(UUID.randomUUID(),4));assertEquals(0,restored.issue(b.id,-1));}
    @Test void separatePressingsHaveSeparateIdsWithStableVintage(){var a=fruit(true,4);var b=fruit(true,4);assertNotEquals(a.id,b.id);assertEquals(a.id,a.copy().id);assertEquals(a.vintage,b.vintage);}
    @org.junit.jupiter.api.Test void tastingTraitsRemainShortAndFollowBatchState(){var b=WineBatch.press(java.util.Collections.nCopies(8,new WineBatch.Fruit(true,5,true)),1);b.cloudy=true;b.aged=b.idealAge()*4;b.darkAged=b.aged;var traits=b.tastingTraits();org.junit.jupiter.api.Assertions.assertTrue(traits.containsAll(java.util.List.of("Sweet","Oaky","Cloudy","Fading")));org.junit.jupiter.api.Assertions.assertTrue(traits.indexOf("Oaky")<traits.indexOf("Cloudy"));org.junit.jupiter.api.Assertions.assertTrue(traits.stream().allMatch(t->t.length()<=32));org.junit.jupiter.api.Assertions.assertEquals(traits,b.copy().tastingTraits());}

}
