plugins {
    id 'architectury-plugin' version '3.4.164'
    id 'dev.architectury.loom' version '1.7.435' apply false
}

architectury {
    minecraft = rootProject.minecraft_version
}

allprojects {
    apply plugin: 'java'
    apply plugin: 'architectury-plugin'
    group = rootProject.maven_group
    version = rootProject.mod_version
    base { archivesName = "${rootProject.archives_base_name}-${project.name}" }
    repositories {
        mavenCentral()
        maven {
            url = 'https://maven.blamejared.com/'
            content { includeGroup 'vazkii.patchouli' }
        }
        maven { url = 'https://maven.architectury.dev/' }
        maven { url = 'https://maven.neoforged.net/releases/' }
    }
    java {
        toolchain.languageVersion = JavaLanguageVersion.of(21)
        withSourcesJar()
    }
    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 21
    }
}

subprojects {
    apply plugin: 'dev.architectury.loom'
    loom { silentMojangMappingsLicense() }
    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        mappings loom.officialMojangMappings()
    }
}
