package io.github.jakediscord.hobbymod.painting;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class PaintingDataTest {
    @Test void shapesAndResolutionsStayBoundedAndDistinct(){for(var s:PaintingData.Shape.values())for(int r:PaintingData.RESOLUTIONS){var d=new PaintingData(s,r);assertEquals(r,Math.min(d.width(),d.height()));assertTrue(d.width()*d.height()<=PaintingData.MAX_PIXELS);}var round=new PaintingData(PaintingData.Shape.ROUND,32);assertFalse(round.inside(0,0));assertTrue(round.inside(16,16));assertEquals(32,new PaintingData(PaintingData.Shape.SQUARE,Integer.MAX_VALUE).resolution);}
    @Test void continuousBrushStrokesHaveNoGapsAndBlendOncePerBatch(){var d=new PaintingData(PaintingData.Shape.SQUARE,64);assertTrue(d.paint(new float[]{0,30,63,30},0xff0000,1,100,0)>0);for(int x=0;x<64;x++)assertEquals(0xff0000,d.pixel(x,30));assertEquals(PaintingData.LINEN,d.pixel(20,31));int revision=d.revision;assertEquals(0,d.paint(new float[]{Float.NaN,1},0,16,100,0));assertEquals(revision,d.revision);d.paint(new float[]{10,10,30,10,10,10},0,4,50,0);assertEquals(PaintingData.mix(PaintingData.LINEN,0,50),d.pixel(20,10));}
    @Test void softBrushHasGradedEdges(){var d=new PaintingData(PaintingData.Shape.SQUARE,32);d.paint(new float[]{16,16},0,16,100,4);assertEquals(0,d.pixel(16,16));assertNotEquals(0,d.pixel(21,16));assertNotEquals(PaintingData.LINEN,d.pixel(21,16));assertEquals(PaintingData.LINEN,d.pixel(24,16));}
    @Test void fillRespectsBoundariesAndRoundCanvasMask(){var d=new PaintingData(PaintingData.Shape.SQUARE,16);d.paint(new float[]{8,0,8,15},0,1,100,2);assertEquals(128,d.paint(new float[]{1,1},0x00ff00,1,100,3));assertEquals(PaintingData.LINEN,d.pixel(10,4));var round=new PaintingData(PaintingData.Shape.ROUND,32);int n=round.paint(new float[]{16,16},0xff0000,1,100,3);assertTrue(n>700 && n<1024);assertEquals(PaintingData.LINEN,round.pixel(0,0));}
    @Test void resizingAndCarryingPreserveArtworkAndSignature(){var d=new PaintingData(PaintingData.Shape.LANDSCAPE,16);d.paint(new float[]{4,4},0x336699,8,100,1);assertTrue(d.resize(128));assertEquals(0x336699,d.pixel(32,32));d.title="Lake";d.author="Painter";d.signed=true;assertFalse(d.resize(32));assertEquals(0,d.paint(new float[]{1,1},0,1,100,0));var copy=PaintingNbt.read(PaintingNbt.save(d),PaintingData.Shape.SQUARE);assertEquals(d.id,copy.id);assertEquals(d.title,copy.title);assertEquals(d.author,copy.author);assertTrue(copy.signed);assertArrayEquals(d.pixels(),copy.pixels());}
    @Test void malformedCompressedRasterCannotAllocateBeyondCanvasOrPartlyOverwriteIt(){var d=new PaintingData(PaintingData.Shape.PANORAMA,128);assertFalse(d.restore(new byte[]{1,2,3}));assertFalse(d.restore(new byte[PaintingData.MAX_PIXELS*4+1025]));assertEquals(PaintingData.LINEN,d.pixel(0,0));assertTrue(d.restore(d.compressed()));var tag=PaintingNbt.save(d);tag.putString("Shape","bad");tag.putInt("Resolution",Integer.MAX_VALUE);var copy=PaintingNbt.read(tag,PaintingData.Shape.ROUND);assertEquals(PaintingData.Shape.ROUND,copy.shape);assertEquals(32,copy.resolution);}
}
