package io.github.jakediscord.hobbymod.gametest;
import io.github.jakediscord.hobbymod.HobbyMod;
import io.github.jakediscord.hobbymod.astronomy.*;
import net.minecraft.core.*;
import net.minecraft.gametest.framework.*;
import net.minecraft.world.*;
import net.minecraft.world.item.*;
import net.minecraft.world.item.context.*;
import net.minecraft.world.level.GameType;
import net.minecraft.world.level.block.*;
import net.minecraft.world.phys.*;
import net.neoforged.neoforge.gametest.*;
@GameTestHolder("hobbymod") @PrefixGameTestTemplate(false)
public final class AstronomyGameTests {
 private static final BlockPos POS=new BlockPos(1,1,1);
 private static void pass(GameTestHelper h,String name){h.succeed();HobbyMod.LOGGER.info("ASTRONOMY_TEST_PASS {}",name);}
 @GameTest(template="aquarium_empty") public static void survivalPlacementConsumesOneAndNeedsHeadroom(GameTestHelper h){var p=h.makeMockPlayer(GameType.SURVIVAL);p.getAbilities().mayBuild=true;p.moveTo(Vec3.atCenterOf(h.absolutePos(POS.north())));p.setYRot(73);h.setBlock(POS.below(),Blocks.STONE);p.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(AstronomyContent.SMALL_ITEM.get(),2));var floor=h.absolutePos(POS.below());var c=new BlockPlaceContext(new UseOnContext(p,InteractionHand.MAIN_HAND,new BlockHitResult(Vec3.atCenterOf(floor),Direction.UP,floor,false)));h.setBlock(POS.above(),Blocks.STONE);h.assertTrue(!((BlockItem)p.getMainHandItem().getItem()).place(c).consumesAction() && p.getMainHandItem().getCount()==2,"Headroom must be required without consuming an item");h.setBlock(POS.above(),Blocks.AIR);h.assertTrue(((BlockItem)p.getMainHandItem().getItem()).place(c).consumesAction() && p.getMainHandItem().getCount()==1,"Telescope placement consumes exactly one");var b=(TelescopeBlockEntity)h.getLevel().getBlockEntity(h.absolutePos(POS));h.assertTrue(Math.abs(b.yaw-73)<.01 && b.aperture()==80,"Placed telescope follows player yaw and has starter aperture");h.setBlock(POS,Blocks.AIR);h.setBlock(POS.above(2),Blocks.STONE);p.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(AstronomyContent.LARGE_ITEM.get()));c=new BlockPlaceContext(new UseOnContext(p,InteractionHand.MAIN_HAND,new BlockHitResult(Vec3.atCenterOf(floor),Direction.UP,floor,false)));h.assertTrue(!((BlockItem)p.getMainHandItem().getItem()).place(c).consumesAction() && p.getMainHandItem().getCount()==1,"Larger optics need headroom for their full arc");h.setBlock(POS.above(2),Blocks.AIR);h.assertTrue(((BlockItem)p.getMainHandItem().getItem()).place(c).consumesAction(),"Large telescope places with full headroom");h.assertTrue(p.getMainHandItem().isEmpty(),"Large placement consumes the actual held equipment");pass(h,"survivalPlacementConsumesOneAndNeedsHeadroom");}
 @GameTest(template="aquarium_empty") public static void mountSaveSanitizesAnglesAndMiningReturnsEquipment(GameTestHelper h){h.setBlock(POS,AstronomyContent.OBSERVATORY.get());var b=(TelescopeBlockEntity)h.getLevel().getBlockEntity(h.absolutePos(POS));b.yaw=21;b.pitch=-45;b.focus=.72f;b.magnification=60;var saved=b.saveWithoutMetadata(h.getLevel().registryAccess());var restored=new TelescopeBlockEntity(b.getBlockPos(),b.getBlockState());restored.loadWithComponents(saved,h.getLevel().registryAccess());h.assertTrue(restored.aperture()==180 && restored.magnification==60 && restored.focus==.72f,"Optical setup survives saving");saved.putFloat("Pitch",Float.NaN);saved.putFloat("Magnification",Float.POSITIVE_INFINITY);restored.loadWithComponents(saved,h.getLevel().registryAccess());h.assertTrue(Float.isFinite(restored.pitch) && Float.isFinite(restored.magnification),"Invalid optics cannot poison rendering");var drops=Block.getDrops(b.getBlockState(),h.getLevel(),b.getBlockPos(),b);h.assertTrue(drops.size()==1 && drops.getFirst().is(AstronomyContent.LARGE_ITEM.get()),"Mining returns one real telescope");pass(h,"mountSaveSanitizesAnglesAndMiningReturnsEquipment");}
 @GameTest(template="aquarium_empty") public static void serverAuthorizationRequiresNearbyExistingMountAndActualJournal(GameTestHelper h){h.setBlock(POS,AstronomyContent.TELESCOPE.get());var p=h.makeMockPlayer(GameType.SURVIVAL);p.getAbilities().mayBuild=true;var pos=h.absolutePos(POS);p.moveTo(Vec3.atCenterOf(pos.north()));h.assertTrue(AstronomyNetworking.allowed(p,pos),"Nearby player may use a real mount");h.assertTrue(!AstronomyNetworking.hasJournal(p),"No free observation journal");var journal=new ItemStack(AstronomyContent.JOURNAL.get());journal.set(net.minecraft.core.component.DataComponents.CUSTOM_NAME,net.minecraft.network.chat.Component.literal("My observing notes"));p.getInventory().add(journal);h.assertTrue(AstronomyNetworking.hasJournal(p),"Actual renamed inventory journal permits recording");p.moveTo(Vec3.atCenterOf(pos.offset(10,0,0)));h.assertTrue(!AstronomyNetworking.allowed(p,pos),"Remote edits rejected");p.moveTo(Vec3.atCenterOf(pos.north()));h.setBlock(POS,Blocks.AIR);h.assertTrue(!AstronomyNetworking.allowed(p,pos),"Removed mount rejected");pass(h,"serverAuthorizationRequiresNearbyExistingMountAndActualJournal");}
 @GameTest(template="aquarium_empty") public static void journalIdentityRoundTripAndSharedCatalog(GameTestHelper h){var d=AstronomyData.get(h.getLevel().getServer());var j=new ObservationJournal();h.assertTrue(j.record(19,.8,18000,100),"Observation recorded");var encoded=AstronomyData.encode(j);var restored=AstronomyData.decode(encoded);h.assertTrue(restored.get(19).completeness==j.get(19).completeness && restored.get(19).observations==1 && restored.get(19).night==0,"Progress and repeated-night limits survive saving");h.assertTrue(!encoded.contains("Stars") && !encoded.contains("Planets"),"Journal stores IDs rather than duplicating the sky");h.assertTrue(d.catalog.targets.equals(new SkyCatalog(d.seed).targets),"Clients derive the same catalog from the shared seed");pass(h,"journalIdentityRoundTripAndSharedCatalog");}
}
