package io.github.jakediscord.hobbymod.gametest;
import io.github.jakediscord.hobbymod.HobbyMod;
import io.github.jakediscord.hobbymod.dj.*;
import net.minecraft.core.*;
import net.minecraft.gametest.framework.*;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.*;
import net.minecraft.world.level.GameType;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.phys.Vec3;
import net.neoforged.neoforge.gametest.*;
@GameTestHolder("hobbymod")
@PrefixGameTestTemplate(false)
public final class DjGameTests {
    private static final BlockPos POS=new BlockPos(1,1,1);
    private static DjBlockEntity studio(GameTestHelper h){h.setBlock(POS.below(),Blocks.STONE);h.setBlock(POS,DjContent.WORKSTATION.get());return (DjBlockEntity)h.getLevel().getBlockEntity(h.absolutePos(POS));}
    private static Player player(GameTestHelper h){var p=h.makeMockPlayer(GameType.SURVIVAL);p.getAbilities().mayBuild=true;p.moveTo(Vec3.atCenterOf(h.absolutePos(POS.offset(0,0,-2))));return p;}
    private static String work(Player p,DjBlockEntity b,int kind,int deck,int value,byte[] data){return DjNetworking.work(p,b,new DjNetworking.Action(b.getBlockPos(),b.revision,kind,deck,value,data));}
    private static void pass(GameTestHelper h,String name){h.succeed();HobbyMod.LOGGER.info("DJ_TEST_PASS {}",name);}
    @GameTest(template="empty") public static void completePatternLayersSurviveDiscAndWorldSave(GameTestHelper h){
        var b=studio(h);var player=player(h);b.claim(player);var song=new MusicProject();song.bars=1;
        for(int channel=0;channel<8;channel++){song.tracks[channel].put(0,new MusicProject.Note(0,48+channel,2,100));song.tracks[channel].put(1,new MusicProject.Note(4,60+channel,2,90));}
        song.tracks[5].instrument=MusicProject.Instrument.FLUTE;song.placeClip(2,0,0);song.placeClip(7,0,1);
        work(player,b,DjNetworking.SAVE,0,0,song.encode());player.getInventory().setItem(0,new ItemStack(DjContent.BLANK.get()));work(player,b,DjNetworking.BURN,0,0,new byte[0]);
        var saved=player.getInventory().getItem(0);var recorded=DjDiscItem.read(saved);
        h.assertTrue(recorded!=null && MusicSynth.schedule(recorded,-1).size()==16,"Recording retains every instrument in both layered patterns");
        h.assertTrue(recorded.tracks[5].instrument==MusicProject.Instrument.FLUTE,"New instrument persists on disc");
        var restored=new DjBlockEntity(b.getBlockPos(),b.getBlockState());restored.loadWithComponents(b.getUpdateTag(h.getLevel().registryAccess()),h.getLevel().registryAccess());
        h.assertTrue(MusicSynth.schedule(restored.projects[0],-1).equals(MusicSynth.schedule(song,-1)),"World save and network tags retain lane-independent full-pattern scheduling");
        pass(h,"completePatternLayersSurviveDiscAndWorldSave");
    }
    @GameTest(template="empty") public static void projectSaveDiscLoadAndInventoryCosts(GameTestHelper h){var b=studio(h);var p=player(h);h.assertTrue(b.claim(p),"Player claims studio");var song=MusicProject.demo();song.title="Village set";work(p,b,DjNetworking.SAVE,0,0,song.encode());h.assertTrue(b.projects[0].title.equals("Village set") && b.projects[0].noteCount()>0,"Song edits save");h.assertTrue(work(p,b,DjNetworking.BURN,0,0,new byte[0]).contains("blank"),"Missing blank disc rejects recording");p.getInventory().setItem(0,new ItemStack(DjContent.BLANK.get(),2));work(p,b,DjNetworking.BURN,0,0,new byte[0]);h.assertTrue(p.getInventory().getItem(0).getCount()==1,"Recording consumes exactly one blank");var disc=p.getInventory().getItem(1);h.assertTrue(DjDiscItem.read(disc)!=null && DjDiscItem.read(disc).title.equals("Village set"),"Recorded item retains editable music");p.setItemInHand(net.minecraft.world.InteractionHand.MAIN_HAND,disc.copy());work(p,b,DjNetworking.LOAD,1,0,new byte[0]);h.assertTrue(b.projects[1].id.equals(song.id) && !p.getMainHandItem().isEmpty(),"Deck loads a reusable disc without consuming it");pass(h,"projectSaveDiscLoadAndInventoryCosts");}
    @GameTest(template="empty") public static void staleMalformedAndUnauthorizedEditsPreserveSong(GameTestHelper h){var b=studio(h);var p=player(h);var other=player(h);b.claim(p);var saved=b.projects[0].encode();h.assertTrue(!b.claim(other),"A second editor cannot steal a live lease");h.assertTrue(work(other,b,DjNetworking.NEW,0,0,new byte[0]).contains("expired"),"Unowned command is denied");work(p,b,DjNetworking.SAVE,0,0,new byte[]{1,2,3});h.assertTrue(java.util.Arrays.equals(saved,b.projects[0].encode()),"Malformed song preserves original");DjNetworking.work(p,b,new DjNetworking.Action(b.getBlockPos(),b.revision+1,DjNetworking.NEW,0,0,new byte[0]));h.assertTrue(java.util.Arrays.equals(saved,b.projects[0].encode()),"Stale command preserves original");work(p,b,DjNetworking.RELEASE,0,0,new byte[0]);h.assertTrue(b.claim(other),"Released lease can be claimed");pass(h,"staleMalformedAndUnauthorizedEditsPreserveSong");}
    @GameTest(template="empty") public static void transportCrossfadeSyncAndSpeakerRange(GameTestHelper h){var b=studio(h);var p=player(h);b.claim(p);b.projects[0]=MusicProject.demo();b.projects[1]=MusicProject.demo();b.projects[1].bpm=90;work(p,b,DjNetworking.PLAY,0,0,new byte[0]);work(p,b,DjNetworking.SYNC,1,0,new byte[0]);h.assertTrue(b.projects[1].bpm==120 && b.started[1]==b.started[0],"Deck sync aligns tempo and beat clock");work(p,b,DjNetworking.CROSS,0,0,new byte[0]);h.assertTrue(Math.abs(b.gain(0)-1)<.001 && b.gain(1)==0,"Crossfade A silences B");work(p,b,DjNetworking.CROSS,0,100,new byte[0]);h.assertTrue(b.gain(0)<.001 && Math.abs(b.gain(1)-1)<.001,"Crossfade B silences A");h.assertTrue(b.range()==24,"Standalone table has local listening range");h.setBlock(POS.offset(1,0,0),DjContent.SPEAKER.get());h.assertTrue(b.range()==48,"Speaker extends range");work(p,b,DjNetworking.STOP,0,0,new byte[0]);h.assertTrue(!b.playing[0],"Stop updates authoritative transport");pass(h,"transportCrossfadeSyncAndSpeakerRange");}
    @GameTest(template="empty",timeoutTicks=100) public static void oneShotEndsWhileLoopingDeckContinues(GameTestHelper h){var b=studio(h);var p=player(h);b.claim(p);b.projects[0]=MusicProject.demo();b.projects[1]=MusicProject.demo();b.projects[0].bars=1;b.projects[0].bpm=200;b.loop[0]=false;work(p,b,DjNetworking.PLAY,0,0,new byte[0]);work(p,b,DjNetworking.PLAY,1,0,new byte[0]);h.runAfterDelay(55,()->{h.assertTrue(!b.playing[0],"One-shot song stops after its effect tail");h.assertTrue(b.playing[1],"Looping song remains playing");pass(h,"oneShotEndsWhileLoopingDeckContinues");});}
    @GameTest(template="empty") public static void pickupAndReloadPreserveBothProjects(GameTestHelper h){var b=studio(h);b.projects[0]=MusicProject.demo();b.projects[1]=MusicProject.demo();b.projects[1].title="Second deck";b.crossfade=27;b.playing[0]=true;var tag=b.saveWithoutMetadata(h.getLevel().registryAccess());var restored=new DjBlockEntity(b.getBlockPos(),b.getBlockState());restored.loadWithComponents(tag,h.getLevel().registryAccess());h.assertTrue(restored.projects[1].title.equals("Second deck") && restored.crossfade==27 && !restored.playing[0],"World save preserves songs and safely stops transport on reload");var drops=Block.getDrops(b.getBlockState(),h.getLevel(),b.getBlockPos(),b);h.assertTrue(drops.size()==1 && drops.getFirst().is(DjContent.TABLE.get()),"Workstation drops once");var data=drops.getFirst().get(net.minecraft.core.component.DataComponents.CUSTOM_DATA);h.assertTrue(data!=null && data.copyTag().getCompound("Studio").contains("Deck1"),"Pickup item contains both complete projects");pass(h,"pickupAndReloadPreserveBothProjects");}
}
