package io.github.jakediscord.hobbymod.dj;
import org.junit.jupiter.api.Test;
import java.io.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
final class MusicProjectTest {
    @Test void projectRoundTripPreservesArrangementNotesAndMix()throws Exception{var p=MusicProject.demo();p.title="My first set";p.author="DJ";p.bpm=137;p.swing=35;p.tracks[4].pan=-75;p.tracks[4].cutoff=42;p.tracks[4].delay=50;p.tracks[4].reverb=25;p.tracks[4].solo=true;p.tracks[5].mute=true;p.tracks[4].arrangement[3]=7;p.tracks[4].put(7,new MusicProject.Note(4,43,8,117));var data=p.encode();var q=MusicProject.decode(data);assertArrayEquals(data,q.encode());assertEquals(p.id,q.id);assertEquals(8,q.tracks[4].notes(7).getFirst().length());assertEquals(7,q.tracks[4].arrangement[3]);}
    @Test void maliciousAndTruncatedFilesAreRejected()throws Exception{var good=MusicProject.demo().encode();for(int size:new int[]{0,31,good.length-1})assertThrows(IOException.class,()->MusicProject.decode(Arrays.copyOf(good,size)));var bad=good.clone();bad[0]=0;assertThrows(IOException.class,()->MusicProject.decode(bad));assertThrows(IOException.class,()->MusicProject.decode(new byte[MusicProject.MAX_BYTES+1]));assertThrows(IOException.class,()->MusicProject.decode(Arrays.copyOf(good,good.length+1)));assertThrows(IllegalArgumentException.class,()->new MusicProject.Note(15,48,2,100));}
    @Test void maximumLegalProjectFitsNetworkBudget()throws Exception{var p=new MusicProject();for(var t:p.tracks)for(int pat=0;pat<8;pat++)for(int i=0;i<48;i++)assertTrue(t.put(pat,new MusicProject.Note(i/3,48+i%3,1,127)));assertTrue(p.encode().length<MusicProject.MAX_BYTES);assertEquals(3072,MusicProject.decode(p.encode()).noteCount());assertFalse(p.tracks[0].put(0,new MusicProject.Note(0,72,1,100)));assertTrue(p.tracks[0].put(0,new MusicProject.Note(0,48,2,80)));}
    @Test void copyAndTransposeDoNotAlterSourcePatterns(){var p=new MusicProject();var t=p.tracks[4];t.put(0,new MusicProject.Note(0,36,4,95));t.copyPattern(0,1);t.transpose(1,-12);assertEquals(36,t.notes(1).getFirst().pitch());t.transpose(1,12);assertEquals(48,t.notes(1).getFirst().pitch());assertEquals(36,t.notes(0).getFirst().pitch());var q=p.copy();q.tracks[4].clear(0);assertEquals(1,p.tracks[4].notes(0).size());}
    @Test void scheduleHonorsSwingArrangementAndSolo(){var p=new MusicProject();p.bars=2;p.bpm=120;p.swing=50;p.tracks[4].put(1,new MusicProject.Note(1,48,2,100));p.tracks[4].arrangement[1]=1;p.tracks[0].put(0,new MusicProject.Note(0,60,1,100));p.tracks[0].arrangement[0]=0;p.tracks[4].solo=true;var events=MusicSynth.schedule(p,-1);assertEquals(1,events.size());assertEquals(Math.round((2+.15625)*MusicSynth.SAMPLE_RATE),events.getFirst().frame());p.tracks[4].mute=true;assertTrue(MusicSynth.schedule(p,-1).isEmpty());}
}
