package io.github.jakediscord.hobbymod.dj;
import org.junit.jupiter.api.Test;
import java.io.*;
import java.nio.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
final class MusicSynthTest {
    private static double rms(byte[] b,int channel){double sum=0;for(int i=channel*2;i<b.length;i+=4){short v=(short)((b[i]&255)|b[i+1]<<8);sum+=(double)v*v;}return Math.sqrt(sum/(b.length/4));}
    @Test void everyInstrumentProducesDistinctBoundedStereoAudio(){var hashes=new HashSet<Integer>();for(var instrument:MusicProject.Instrument.values()){var p=new MusicProject();p.tracks[0].instrument=instrument;p.tracks[0].put(0,new MusicProject.Note(0,60,8,110));byte[] buffer=new byte[MusicSynth.SAMPLE_RATE*4/2];new MusicSynth(p,0,false,0).read(buffer,buffer.length/4);assertTrue(rms(buffer,0)>80,instrument.label());hashes.add(Arrays.hashCode(buffer));}assertEquals(9,hashes.size());}
    @Test void renderedAudioIsDeterministicAcrossBufferSizes(){var p=MusicProject.demo();p.tracks[4].delay=75;p.tracks[6].reverb=80;byte[] full=new byte[8192*4];new MusicSynth(p,-1,true,0).read(full,8192);var other=new MusicSynth(p,-1,true,0);byte[] block=new byte[1024*4],split=new byte[full.length];for(int i=0;i<8;i++){other.read(block,1024);System.arraycopy(block,0,split,i*block.length,block.length);}assertArrayEquals(full,split);}
    @Test void muteAndPanHaveAudibleEffects(){var p=new MusicProject();p.tracks[4].put(0,new MusicProject.Note(0,48,8,100));p.tracks[4].pan=-100;byte[] b=new byte[4096*4];new MusicSynth(p,0,false,0).read(b,4096);assertTrue(rms(b,0)>100);assertEquals(0,rms(b,1),1);p.tracks[4].mute=true;new MusicSynth(p,0,false,0).read(b,4096);assertEquals(0,rms(b,0),1);}
    @Test void seekingMaintainsSustainedNotes(){var p=new MusicProject();p.tracks[7].put(0,new MusicProject.Note(0,60,16,100));byte[] pcm=new byte[4096*4];new MusicSynth(p,0,false,MusicSynth.SAMPLE_RATE).read(pcm,4096);assertTrue(rms(pcm,0)>100,"Seeking into a held pad must retain its voice");}
    @Test void effectsChangeAudioAndRemainWithinPcmRange(){var dry=MusicProject.demo();var wet=dry.copy();wet.tracks[6].delay=100;wet.tracks[6].reverb=100;wet.tracks[4].cutoff=10;byte[] a=new byte[16384*4],b=new byte[a.length];new MusicSynth(dry,-1,false,0).read(a,a.length/4);new MusicSynth(wet,-1,false,0).read(b,b.length/4);assertFalse(Arrays.equals(a,b));assertTrue(rms(b,0)>100);for(int i=0;i<b.length;i+=2){short sample=(short)((b[i]&255)|b[i+1]<<8);assertTrue(sample>-32768 && sample<32767,"Mixer should preserve headroom");}}
    @Test void loopingAndWavHeaderHaveCorrectLengths()throws Exception{var p=MusicProject.demo();p.bars=1;p.bpm=200;var synth=new MusicSynth(p,0,true,0);byte[] b=new byte[4096*4];long total=p.barFrames()+5000;for(long i=0;i<total;){int frames=(int)Math.min(4096,total-i);synth.read(b,frames);i+=frames;}assertEquals(5000,synth.frame());var out=new ByteArrayOutputStream();MusicSynth.wav(p,out);byte[] wav=out.toByteArray();assertEquals("RIFF",new String(wav,0,4,java.nio.charset.StandardCharsets.US_ASCII));assertEquals("WAVE",new String(wav,8,4,java.nio.charset.StandardCharsets.US_ASCII));var head=ByteBuffer.wrap(wav).order(ByteOrder.LITTLE_ENDIAN);assertEquals(2,head.getShort(22));assertEquals(MusicSynth.SAMPLE_RATE,head.getInt(24));assertEquals(wav.length-44,head.getInt(40));assertEquals((p.durationFrames()+MusicSynth.SAMPLE_RATE)*4+44,wav.length);}
}
